const CarBrands=[
    {
        id:1,
        name:'BMW'
    },
    {
        id:2,
        name:'Audi'
    },
    {
        id:3,
        name:'Ford'
    }
]

const Pricing=[
    {
        id:1,
        amount:'5000$'
    },
    {
        id:2,
        amount:'10000$'
    },
    {
        id:3,
        amount:'20000$'
    },
    {
        id:4,
        amount:'50000$'
    },
    {
        id:5,
        amount:'100000$'
    }
]

const Category=[
    {
        id:1,
        name:'SUV',
        icon:'./suv.png'
    },
    {
        id:2,
        name:'Sedan',
        icon:'https://cdn-icons-png.flaticon.com/128/3202/3202003.png'
    },
    {
        id:3,
        name:'Hatchback',
        icon:'https://cdn-icons-png.flaticon.com/128/5035/5035167.png'
    },
    {
        id:4,
        name:'Electric',
        icon:'./electric-car.png'
    },
    {
        id:5,
        name:'Truck',
        icon:'./pickup-truck.png'
    },
    {
        id:6,
        name:'Hybrid',
        icon:'./hybrid-car.png'
    },
    {
        id:7,
        name:'Coupe',
        icon:'./coupe.png'
    },
    {
        id:8,
        name:'Convertible',
        icon:'https://cdn-icons-png.flaticon.com/128/5035/5035202.png'
    },
    {
        id:9,
        name:'Van',
        icon:'https://cdn-icons-png.flaticon.com/128/1433/1433678.png'
    },
]
export default{
    CarBrands,
    Pricing,
    Category
}